### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/dsci_532_group_04#42]
Hey Group 4, congrats on wrapping up milestone 2. Glad to see your dashboard constantly improving. I'm glad to see you've managed to find a good balance with each of the components you wanted to include. You manage to provide users with access to a great deal of information which should make your app very useful. 
Here are a few points I think could be improved:
- Forgot to download CSV for map, so it's dead now since your link is dead
- Given limited year range, the slider isn't really helpful for the line plots and it doesn't apply to the scatter plot, so I think it'd be better to have it only apply to the map (and place it with the map, e.g. as a vertical slider next to it)
- Problem with outliers for some factors (e.g. infant deaths), should present data as per capita where appropriate
- Having a fixed z-scale for the map would be better as it'd make it easier to see changes with time
- Map has too much whitespace around it
- Can't see all selected countries/continents in dropdown
- If data isn't available for all countries for some factors, it may be worth having a small disclaimer under the plot stating this

**Comment by debanandasarkar** [comment]
The changes below are implemented in R version of dashboard. We are enhancing the R version only as we have decided to move forward with it.
- Added units for x axis in scatter plot
- Added dynamic disclaimer for missing data points in scatter plot
- All the factors are already scaled appropriately. Apparently, countries like India, Nigeria, Pakistan etc have very very high Infant mortality per 1000 population, and we have to live with it.

We will post updates as we address the remaining items.

**Comment by debanandasarkar** [comment]
Removed disclaimer from the scatterplot as we are using the entire date range and averaging the x and y axis for all the countries.

**Comment by YikiSu** [comment]
- Forgot to download CSV for map, so it's dead now since your link is dead
   - Done. 
- Given limited year range, the slider isn't really helpful for the line plots and it doesn't apply to the scatter plot, so I think it'd be better to have it only apply to the map (and place it with the map, e.g. as a vertical slider next to it)
  - We decided to generate average life expectancy information in the scatterplot based on the year range selected, this is also based on the feedback we received from milestone 3.
- Problem with outliers for some factors (e.g. infant deaths), should present data as per capita where appropriate
  - Data is already scaled therefore, no further actions are needed. We have added proper units in the X-axis to make it clearer to audiences.
- Having a fixed z-scale for the map would be better as it'd make it easier to see changes with time
  - Done. 
- Map has too much whitespace around it
  - White space is removed.
- Can't see all selected countries/continents in dropdown
  - This is not feasible at this stage and we had a discussion with Chris. He was fine that if we truly can't find a solution. The values can be seen in the legend. 
- If data isn't available for all countries for some factors, it may be worth having a small disclaimer under the plot stating this
  - This is not applicable anymore based on the changes done as per feedback from milestone 3.
